### ISSUE TITLE
Dynamic list of projects

### ISSUE THREAD

**Issue by felickz** [advanced-security/monorepo-code-scanning-action#11]
I [attempted ](https://github.com/advanced-security/sample-javascript-monorepo/actions/runs/11522546465/workflow?pr=2)to dynamically build the list of folders to scan and write that file and pass in but it appears that the next step will checkout overtop of my file and it will no longer exist

```yaml
    # Only checkout the latest commit and just the packages folder
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: "packages/"
        #   EX:
        #   {
        # "javascript": {
        #     "babel-cli": [
        #         "packages/babel-cli"
        #     ],
        #     "babel-code-frame": [
        #         "packages/babel-code-frame"
        #     ],
        #     "babel-compat-data": [
        #         "packages/babel-compat-data"
        #     ], 
        # ............ (for each directory under projects )
      - name: Build language based projects JSON for each package in the monorepo
        run: |
          #!/bin/bash
          json="{ \"javascript\": {"
          for dir in packages/*/
          do
              folder_name=$(basename "$dir")
              json+="\"$folder_name\": [ \"packages/$folder_name\" ],"
          done
          json="${json%,}}}"
          echo -e "$json" > dynamic-projects.json
          cat dynamic-projects.json
      - name: Spot changes to projects
        id: changes
        uses: advanced-security/monorepo-code-scanning-action/changes@main
        with:
          projects-json: dynamic-projects.json

```

Error in `spot changes to projects`:
>Error: Failed to read projects JSON: Error: ENOENT: no such file or directory, open 'dynamic-projects.json'
